version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt

# Сборка для разных языков
build:
  commands:
    - git submodule update --init --recursive
    - echo "Building Russian version..."
    - sphinx-build -b html -D language=ru docs/ _build/ru/
    - echo "Building English version..."
    - sphinx-build -b html -D language=en docs/ _build/en/