version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt

build:
  commands:
    - echo "Building documentation..."
    - pip install -r docs/requirements.txt
    - sphinx-build -b html docs/ _build/html/