version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
     # You can also specify other tool versions:
     # nodejs: "18"
     # rust: "1.64"

sphinx:
  configuration: docs/conf.py

python:
   install:
   - requirements: docs/requirements.txt

# Явно укажите дополнительные сборки для языков
build:
  jobs:
    pre_build:
      - echo "Building multilingual documentation"
    
    # Сборка для каждого языка
    extra_builds:
      - name: "Build English version"
        command: sphinx-build -b html -D language=en docs/ _build/en
   
# Build PDF & ePub
#formats:
#  - htmlzip
#  - pdf
