version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
     # You can also specify other tool versions:
     # nodejs: "18"
     # rust: "1.64"

sphinx:
  configuration: docs/conf.py

python:
   install:
   - requirements: docs/requirements.txt
 
# Build PDF & ePub
#formats:
#  - htmlzip
#  - pdf
